# Generated by Django 4.1.1 on 2022-10-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youtube',
            new_name='social_linkedin',
        ),
    ]
