# Generated by Django 4.1.1 on 2023-01-07 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_skill_created_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 7, 16, 48, 26, 989459, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
